@template.layout.main(content = @`
 <div class="home">
      <h1>Bem-vindo ao IFBA Medical Group</h1>
          </div>
<section class="hero-landing">
  <div class="hero-inner">
    <div class="hero-text">
       

      <p class="subtitle">Agendamentos, pacientes e profissionais — tudo num lugar só 😊.</p>
<section class="home-1">
      <div class="home-2">
        <a href="/login" class="btn-home">Entrar</a>
        <a href="/cadastro" class="btn-register">Criar conta</a>
      </div>
</section>
    </div>

    <div class="hero-visual">
      <img src="/img/homeImg.png" alt="Ilustração clínica" />
    </div>
  </div>
</section>

<section class="section">
        <div class="services">
  <div class="card">
    <h3>📅 Agendamentos rápidos</h3>
    <p>Marque consultas em poucos cliques.</p>
  </div>
  <div class="card">
    <h3>🩺 Profissionais qualificados</h3>
    <p>Busque por especialidade e agenda disponível.</p>
  </div>
  <div class="card">
    <h3>🔐 Segurança</h3>
    <p>Dados criptografados e controle de acesso.</p>
  </div>
  </div>
</section>
 <div >
<section class="testimonials">
    <h2>O que dizem nossos pacientes</h2>
    <div class="testimonial-cards">
        <div class="testimonial">
            <img src="https://randomuser.me/api/portraits/women/44.jpg" alt="Paciente 1">
            <h4>Maria Oliveira</h4>
            <p>“Fui muito bem atendida! Equipe atenciosa e exames rápidos.”</p>
            <div class="stars">⭐⭐⭐⭐⭐</div>
        </div>
        <div class="testimonial">
            <img src="https://randomuser.me/api/portraits/men/32.jpg" alt="Paciente 2">
            <h4>João Santos</h4>
            <p>“Ambiente limpo e organizado. Recomendo!”</p>
            <div class="stars">⭐⭐⭐⭐</div>
        </div>
        <div class="testimonial">
            <img src="https://randomuser.me/api/portraits/women/68.jpg" alt="Paciente 3">
            <h4>Larissa Dias</h4>
            <p>“Consulta com o clínico foi excelente. Muito profissional.”</p>
            <div class="stars">⭐⭐⭐⭐⭐</div>
        </div>
        <div class="testimonial">
    <img src="https://randomuser.me/api/portraits/men/65.jpg" alt="Paciente 4">
    <h4>Carlos Mendes</h4>
    <p>“O agendamento foi fácil e rápido. Atendimento excelente do início ao fim.”</p>
    <div class="stars">⭐⭐⭐⭐⭐</div>
</div>
<div class="testimonial">
    <img src="https://randomuser.me/api/portraits/women/22.jpg" alt="Paciente 5">
    <h4>Ana Beatriz</h4>
    <p>“Gostei muito do serviço de curativo. Profissionais muito cuidadosos.”</p>
    <div class="stars">⭐⭐⭐⭐</div>
</div>

    </div>
</section>
</div>

        </div>
    </section>
`)
