spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: redefinirsenhasystem6@gmail.com
    password: fcvh fwwg bdcd uzms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

logging:
  level:
    org.hibernate: ERROR
    org.springframework.orm.jpa: DEBUG
    com.yourpackage: DEBUG

gg:
  jte:
    development-mode: false
    use-precompiled-templates: true
    templateLocation: src/main/resources/jte
